/* Generated by Report Generator v3.7 (R2009b) */
var gHomeSys = "ieee_80211n";
var gNumSys = 17;
var gFrameID = {
"frameset_main":"ieee_80211n_slwebview_main_frameset",
"explorer":"ieee_80211n_slwebview_explorer",
"frameset_model":"ieee_80211n_slwebview_frame",
"model":"ieee_80211n_slwebview_model",
"web":"ieee_80211n_slwebview_web"};
var gIDMap = {
"ieee_80211n":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"ieee_80211n/Decoder":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"ieee_80211n/IQ demapping":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"},
"ieee_80211n/IQ mapping  + codifica":{"target":"slwebview_4.svg","thumb":"slwebview_4_tb.png"},
"ieee_80211n/Performance Analysis":{"target":"slwebview_5.svg","thumb":"slwebview_5_tb.png"},
"ieee_80211n/STBC + OFDM":{"target":"slwebview_6.svg","thumb":"slwebview_6_tb.png"},
"ieee_80211n/Decoder/Deinterleaver 2":{"target":"slwebview_7.svg","thumb":"slwebview_7_tb.png"},
"ieee_80211n/Decoder/Deinterleaver1":{"target":"slwebview_8.svg","thumb":"slwebview_8_tb.png"},
"ieee_80211n/IQ demapping/Combiner + FFT":{"target":"slwebview_9.svg","thumb":"slwebview_9_tb.png"},
"ieee_80211n/IQ mapping  + codifica/BCH  Encoding":{"target":"slwebview_10.svg","thumb":"slwebview_10_tb.png"},
"ieee_80211n/IQ mapping  + codifica/Generazione flussi  spaziali":{"target":"slwebview_11.svg","thumb":"slwebview_11_tb.png"},
"ieee_80211n/IQ mapping  + codifica/Interleaver":{"target":"slwebview_12.svg","thumb":"slwebview_12_tb.png"},
"ieee_80211n/IQ mapping  + codifica/Interleaver1":{"target":"slwebview_13.svg","thumb":"slwebview_13_tb.png"},
"ieee_80211n/IQ mapping  + codifica/Mapping1":{"target":"slwebview_14.svg","thumb":"slwebview_14_tb.png"},
"ieee_80211n/IQ mapping  + codifica/Mapping2":{"target":"slwebview_15.svg","thumb":"slwebview_15_tb.png"},
"ieee_80211n/STBC + OFDM/OFDMtx completo t1":{"target":"slwebview_16.svg","thumb":"slwebview_16_tb.png"},
"ieee_80211n/STBC + OFDM/OFDMtx t0":{"target":"slwebview_17.svg","thumb":"slwebview_17_tb.png"}};

